### ISSUE TITLE
Application crash on sdk version 3.9.1

### ISSUE THREAD

**Issue by MaksymZavada** [webex/webex-android-sdk#142]
Hello!)

We updated the SDK to version 3.9.1 on Android, but after the update, our app started crashing. 
Tell me please:
1. Are you aware of this problem?
2. When to expect a fix?
3. Is there any workaround to solve the problem?

I've added an example below:

# Crashlytics - Stack trace
# Application: ua.alfabank.mobile.android
# Platform: android
# Version: 3.13.0 (527)
# Issue: 224d853e55a9b4b2676ff87bf5c1f879
# Session: 64B939AB011400012ACDDBF69B91D2F2_DNE_0_v2
# Date: Thu Jul 20 2023 16:48:14 GMT+0300 (Eastern European Summer Time)

Fatal Exception: java.lang.IllegalStateException: The viewmodel IOmniusServiceBridge is destroyed
       at com.ciscowebex.androidsdk.internal.IOmniusServiceBridge.addLibsLoadingTime(IOmniusServiceBridge.java:764)
       at com.ciscowebex.androidsdk.OmniusWrapper.addLibsLoadTimeMetrics(OmniusWrapper.kt:557)
       at com.ciscowebex.androidsdk.Webex.<init>(Webex.kt:86)
       at ua.alfabank.mobile.android.zendeskchat.domain.WebexCallProcessor2.createWebex(WebexCallProcessor2.kt:66)
       at ua.alfabank.mobile.android.zendeskchat.domain.WebexCallProcessor2.call(WebexCallProcessor2.kt:86)
       at ua.alfabank.mobile.android.zendeskchat.presentation.viewmodel.VideoChatCallViewModel.initWebexAndCall(VideoChatCallViewModel.kt:94)
       at ua.alfabank.mobile.android.zendeskchat.presentation.viewmodel.VideoChatCallViewModel.init$lambda-0(VideoChatCallViewModel.kt:86)
       at ua.alfabank.mobile.android.zendeskchat.presentation.viewmodel.VideoChatCallViewModel.lambda$xN42U0ULKHzU_wg4atdj1v1WN0E(VideoChatCallViewModel.kt)
       at ua.alfabank.mobile.android.zendeskchat.presentation.viewmodel.-$$Lambda$VideoChatCallViewModel$xN42U0ULKHzU_wg4atdj1v1WN0E.run(lambda:8)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7945)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:603)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
       
       

Thanks in advance.

**Comment by MaksymZavada** [comment]
Hello,

is there any update on this issue?

**Comment by MaksymZavada** [comment]
Hello,
is there any update on this issue?
