### ISSUE TITLE
Crash app related Webex SDK - com.webex.wme.WifiStatus.CheckReachableVia

### ISSUE THREAD

**Issue by duybuiappliedmesh** [webex/webex-android-sdk#92]
Hi Webex Team
I got a crash while using SDK, this is first time I saw this crash.

I'm using **com.ciscowebex:androidsdk:2.7.0.6-SNAPSHOT@aar**
Compile SDK: **30**
Target SDK: **30**

`
Fatal Exception: java.lang.SecurityException: getDataNetworkTypeForSubscriber
       at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
       at android.os.Parcel.createException(Parcel.java:2357)
       at android.os.Parcel.readException(Parcel.java:2340)
       at android.os.Parcel.readException(Parcel.java:2282)
       at com.android.internal.telephony.ITelephony$Stub$Proxy.getNetworkTypeForSubscriber(ITelephony.java:8881)
       at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:3063)
       at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:3027)
       at com.webex.wme.WifiStatus.CheckReachableVia(WifiStatus.java:54)
`

**Comment by jbenyovs** [comment]
@duybuiappliedmesh would you mind checking if the same error is reproducible with the 2.8 KitchenSink app as well? If it is, please describe the full steps to reproduce the issue and provide us complete verbose client sided logs. If it is easier you can also open a support ticket with us devsupport@webex.com so that we can continue the conversation there. Thank you

**Comment by duybuiappliedmesh** [comment]
Hi jbenyovs

I can't check with KitchenSink app, because it's not my phone. The log I collected above from Firebase Crashlytics - from my customer's phone. I also can't reproduce from my side. 
The crash happen when user join a room
User device: Android 11

**Comment by jbenyovs** [comment]
@duybuiappliedmesh  I can see that you opened a ticket with us for the same. We will continue the conversation and the troubleshooting over there. Thanks

**Comment by kaowneaw** [comment]
android sdk v2.8.0 it work for me but have problem with sound plz check
